version: '3.7'
services:
  client:
    build:
      network: host
      context: .
      dockerfile: docker/client/Dockerfile
  server:
    build:
      network: host
      context: .
      dockerfile: docker/server/Dockerfile
